package LimpaTudo;

import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno02.itb
 */
public class Cadastro_Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Produtos
     */
    public Cadastro_Produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        CodBarras = new javax.swing.JLabel();
        ctCodBarras = new javax.swing.JTextField();
        descricao = new javax.swing.JLabel();
        ctDescricao = new javax.swing.JTextField();
        ncm = new javax.swing.JLabel();
        ctNCM = new javax.swing.JTextField();
        quantidade = new javax.swing.JLabel();
        ctQtde = new javax.swing.JTextField();
        peso = new javax.swing.JLabel();
        ctPeso = new javax.swing.JTextField();
        preco = new javax.swing.JLabel();
        ctPreco = new javax.swing.JTextField();
        situacao = new javax.swing.JLabel();
        ccSituacao = new javax.swing.JComboBox<>();
        CodClas = new javax.swing.JLabel();
        ctCodClas = new javax.swing.JTextField();
        btBuscaCodClas = new javax.swing.JButton();
        classificacao = new javax.swing.JLabel();
        ctClassificacao = new javax.swing.JTextField();
        btIncluir = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        codigo.setText("Código");

        ctCodigo.setEnabled(false);

        CodBarras.setText("Cód. Barras");

        descricao.setText("Descrição");

        ncm.setText("NCM");

        quantidade.setText("Qtde");

        peso.setText("Peso");

        preco.setText("Preço");

        situacao.setText("Situação");

        ccSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));

        CodClas.setText("Cód. Clas.");

        ctCodClas.setEnabled(false);

        btBuscaCodClas.setText("...");
        btBuscaCodClas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaCodClasActionPerformed(evt);
            }
        });

        classificacao.setText("Classificação");

        ctClassificacao.setEnabled(false);

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/32/incluir.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/32/avancar.png"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/32/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ncm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(quantidade)
                .addGap(77, 77, 77)
                .addComponent(peso)
                .addGap(73, 73, 73)
                .addComponent(preco)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(situacao)
                .addGap(57, 57, 57)
                .addComponent(CodClas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classificacao)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ccSituacao, 0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ctNCM))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(codigo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CodBarras))
                            .addComponent(ctCodigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ctCodBarras)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descricao)
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ctCodClas, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(ctQtde))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btBuscaCodClas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctClassificacao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ctPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodBarras)
                    .addComponent(descricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncm)
                    .addComponent(quantidade)
                    .addComponent(peso)
                    .addComponent(preco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctNCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(situacao)
                    .addComponent(CodClas)
                    .addComponent(classificacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctCodClas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaCodClas)
                    .addComponent(ctClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair)
                    .addComponent(btIncluir)
                    .addComponent(btGravar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(424, 344));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        limpacampos();
        habilitacampos();
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        gravar();
    }//GEN-LAST:event_btGravarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btBuscaCodClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaCodClasActionPerformed
        Cadastro_Classificacao_GetDados classificacao = new Cadastro_Classificacao_GetDados();
        buscaClassificacao();
    }//GEN-LAST:event_btBuscaCodClasActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        UnicaConexao con = new UnicaConexao();
        con.conectar();
    }//GEN-LAST:event_formWindowActivated

    private void buscaClassificacao(){
        Cadastro_Classificacao_Dialog classificacaox = new Cadastro_Classificacao_Dialog();
        
        ctCodClas.setText(Cadastro_Classificacao_GetDados.yCodClas);
        ctClassificacao.setText(Cadastro_Classificacao_GetDados.yClassificacao);
    }
    
    private void limpacampos()
    {
        ctCodigo.setText("");
        ctCodBarras.setText("");
        ctDescricao.setText("");
        ctNCM.setText("");
        ctQtde.setText("");
        ctPeso.setText("");
        ctPreco.setText("");
        ccSituacao.setSelectedIndex(-1);
        ctCodClas.setText("");
        ctClassificacao.setText("");
    }
    
    private void habilitacampos()
    {
        ctCodBarras.setEditable(true);
        ctDescricao.setEditable(true);
        ctNCM.setEditable(true);
        ctQtde.setEditable(true);
        ctPeso.setEditable(true);
        ctPreco.setEditable(true);
    }
    
    private void gravar()
    {
        if(ctCodBarras.getText().equals("") || ctDescricao.getText().equals("") ||
                ctNCM.getText().equals("") || ctQtde.getText().equals("") ||
                ctPeso.getText().equals("") || ctPreco.getText().equals("") ||
                ctCodClas.getText().equals("") || ctClassificacao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Algum(ns) campo(s) está(ão) vazio(s)!!", 
                    "Erro", JOptionPane.INFORMATION_MESSAGE);
            ctCodBarras.requestFocus();
            ctDescricao.requestFocus();
            ctNCM.requestFocus();
            ctQtde.requestFocus();
            ctPeso.requestFocus();
            ctPreco.requestFocus();
            ctCodClas.requestFocus();
            ctClassificacao.requestFocus();
            return;
        }
        
        String xCodBarras = ctCodBarras.getText();
        String xDescricao = ctDescricao.getText();
        String xNCM = ctNCM.getText();
        String xQtde = ctQtde.getText();
        String xPeso = ctPeso.getText();
        String xPreco = ctPreco.getText();
        String xSituacao = ccSituacao.getSelectedItem().toString();
        int xCodClas = Integer.parseInt(ctCodClas.getText());
        
        try{
            String sql = "INSERT INTO PRODUTOS(codigo_de_barras, descricao, ncm,"
                    + "quantidade, peso, preco, situacao, cod_classificacao) VALUES('"+ xCodBarras + "','" +
                    xDescricao + "','" + xNCM + "','" + xQtde + "','" + xPeso + "','" + 
                    xPreco + "','" + xSituacao + "','" + xCodClas + "')";
            
            System.out.println(sql);
            Statement stm = VariaveisPublicas.ConexaoPadrao.createStatement();
            stm.executeUpdate(sql);
            stm.close();
            JOptionPane.showMessageDialog(rootPane, "Produto cadastrado!",
                    "Cadastro de Produtos", JOptionPane.INFORMATION_MESSAGE);
            limpacampos();
        }
        
        catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(Cadastro_Produtos.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodBarras;
    private javax.swing.JLabel CodClas;
    private javax.swing.JButton btBuscaCodClas;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> ccSituacao;
    private javax.swing.JLabel classificacao;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField ctClassificacao;
    private javax.swing.JTextField ctCodBarras;
    private javax.swing.JTextField ctCodClas;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JTextField ctDescricao;
    private javax.swing.JTextField ctNCM;
    private javax.swing.JTextField ctPeso;
    private javax.swing.JTextField ctPreco;
    private javax.swing.JTextField ctQtde;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel ncm;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel quantidade;
    private javax.swing.JLabel situacao;
    // End of variables declaration//GEN-END:variables

    private Cadastro_Classificacao_Dialog Cadastro_Classificacao_Dialog() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
