/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Relatorios.Rel_cidades;
import Relatorios.Rel_clientes;
import Relatorios.Rel_funcionarios;
import Relatorios.Rel_notas_fiscais;
import Relatorios.Rel_pedidos;
import Relatorios.Rel_produtos;
import Relatorios.Rel_usuarios;

/**
 *
 * @author Ronde
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoMenu = new javax.swing.JLabel();
        jMenuBar_Menu = new javax.swing.JMenuBar();
        jMenu_Cadastro = new javax.swing.JMenu();
        jMenuItem_CadastroCargos = new javax.swing.JMenuItem();
        jMenuItem_CadastroCidades = new javax.swing.JMenuItem();
        jMenuItem_CadastroClientes = new javax.swing.JMenuItem();
        jMenuItem_CadastroFuncionarios = new javax.swing.JMenuItem();
        jMenuItem_CadastroProdutos = new javax.swing.JMenuItem();
        jMenuItem_CadastroUsuarios = new javax.swing.JMenuItem();
        jMenu_Pedidos = new javax.swing.JMenu();
        jMenu_PedidosCompras = new javax.swing.JMenu();
        jMenuItem_PedidosEmissaoCompras = new javax.swing.JMenuItem();
        jMenuItem_PedidosLiberacaoCompras = new javax.swing.JMenuItem();
        jMenuItem_PedidosCancelamentoCompras = new javax.swing.JMenuItem();
        jMenu_PedidosVendas = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_PedidosEmissaoVendas = new javax.swing.JMenuItem();
        jMenuItem_PedidosLiberacaovendas = new javax.swing.JMenuItem();
        jMenuItem_PedidosCancelamentovendas = new javax.swing.JMenuItem();
        jMenu_Notasfiscais = new javax.swing.JMenu();
        jMenu_NfEntradaNf = new javax.swing.JMenu();
        jMenuItem_EmissaoEntradaNf = new javax.swing.JMenuItem();
        jMenuItem_CancelamentoEntradaNf = new javax.swing.JMenuItem();
        jMenu_NfSaidaNf = new javax.swing.JMenu();
        jMenuItem_EmissaoSaidaNf = new javax.swing.JMenuItem();
        jMenuItem_CancelamentoSaidaNf = new javax.swing.JMenuItem();
        jMenu_Consultas = new javax.swing.JMenu();
        jMenuItem_ConsultasCidades = new javax.swing.JMenuItem();
        jMenuItem_ConsultasClientes = new javax.swing.JMenuItem();
        jMenuItem_ConsultasFuncionarios = new javax.swing.JMenuItem();
        jMenuItem_ConsultasNf = new javax.swing.JMenuItem();
        jMenuItemConsultasPedidos = new javax.swing.JMenuItem();
        jMenuItemConsultasProdutos = new javax.swing.JMenuItem();
        jMenuItem_ConsultasUsuarios = new javax.swing.JMenuItem();
        jMenu_Relatorios = new javax.swing.JMenu();
        jMenuItem_RelatoriosCidades = new javax.swing.JMenuItem();
        jMenuItem_RelatoriosClientes = new javax.swing.JMenuItem();
        jMenuItem_RelatoriosFuncionarios = new javax.swing.JMenuItem();
        jMenuItem_RelatoriosNf = new javax.swing.JMenuItem();
        jMenuItem_RelatoriosPedidos = new javax.swing.JMenuItem();
        jMenuItem_RelatoriosProdutos = new javax.swing.JMenuItem();
        jMenuItem_RelatoriosUsuarios = new javax.swing.JMenuItem();
        jMenu_Sobre = new javax.swing.JMenu();
        jMenuItem_SobreSistema = new javax.swing.JMenuItem();
        jMenuItem_SobreAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        fundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/abstrato_azul.jpg"))); // NOI18N

        jMenu_Cadastro.setText("Cadastro");
        jMenu_Cadastro.setToolTipText("");

        jMenuItem_CadastroCargos.setText("Cargos");
        jMenuItem_CadastroCargos.setToolTipText("");
        jMenuItem_CadastroCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroCargosActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_CadastroCargos);

        jMenuItem_CadastroCidades.setText("Cidades");
        jMenuItem_CadastroCidades.setToolTipText("");
        jMenuItem_CadastroCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroCidadesActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_CadastroCidades);

        jMenuItem_CadastroClientes.setText("Clientes");
        jMenuItem_CadastroClientes.setToolTipText("");
        jMenuItem_CadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroClientesActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_CadastroClientes);

        jMenuItem_CadastroFuncionarios.setText("Funcionários");
        jMenuItem_CadastroFuncionarios.setToolTipText("");
        jMenuItem_CadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroFuncionariosActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_CadastroFuncionarios);

        jMenuItem_CadastroProdutos.setText("Produtos");
        jMenuItem_CadastroProdutos.setToolTipText("");
        jMenuItem_CadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroProdutosActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_CadastroProdutos);

        jMenuItem_CadastroUsuarios.setText("Usuários");
        jMenuItem_CadastroUsuarios.setToolTipText("");
        jMenuItem_CadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroUsuariosActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_CadastroUsuarios);

        jMenuBar_Menu.add(jMenu_Cadastro);

        jMenu_Pedidos.setText("Pedidos");
        jMenu_Pedidos.setToolTipText("");

        jMenu_PedidosCompras.setText("Compras");
        jMenu_PedidosCompras.setToolTipText("");

        jMenuItem_PedidosEmissaoCompras.setText("Emissão");
        jMenuItem_PedidosEmissaoCompras.setToolTipText("Abre o Menu Emissão de Pedidos");
        jMenuItem_PedidosEmissaoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidosEmissaoComprasActionPerformed(evt);
            }
        });
        jMenu_PedidosCompras.add(jMenuItem_PedidosEmissaoCompras);

        jMenuItem_PedidosLiberacaoCompras.setText("Liberação");
        jMenuItem_PedidosLiberacaoCompras.setToolTipText("Abre o Menu Liberação de Pedidos");
        jMenuItem_PedidosLiberacaoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidosLiberacaoComprasActionPerformed(evt);
            }
        });
        jMenu_PedidosCompras.add(jMenuItem_PedidosLiberacaoCompras);

        jMenuItem_PedidosCancelamentoCompras.setText("Cancelamento");
        jMenuItem_PedidosCancelamentoCompras.setToolTipText("Abre o Menu Cancelamento de Pedidos");
        jMenuItem_PedidosCancelamentoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidosCancelamentoComprasActionPerformed(evt);
            }
        });
        jMenu_PedidosCompras.add(jMenuItem_PedidosCancelamentoCompras);

        jMenu_Pedidos.add(jMenu_PedidosCompras);

        jMenu_PedidosVendas.setText("Vendas");
        jMenu_PedidosVendas.setToolTipText("");
        jMenu_PedidosVendas.add(jSeparator1);

        jMenuItem_PedidosEmissaoVendas.setText("Emissão");
        jMenuItem_PedidosEmissaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidosEmissaoVendasActionPerformed(evt);
            }
        });
        jMenu_PedidosVendas.add(jMenuItem_PedidosEmissaoVendas);

        jMenuItem_PedidosLiberacaovendas.setText("Liberação");
        jMenuItem_PedidosLiberacaovendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidosLiberacaovendasActionPerformed(evt);
            }
        });
        jMenu_PedidosVendas.add(jMenuItem_PedidosLiberacaovendas);

        jMenuItem_PedidosCancelamentovendas.setText("Cancelamento");
        jMenuItem_PedidosCancelamentovendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidosCancelamentovendasActionPerformed(evt);
            }
        });
        jMenu_PedidosVendas.add(jMenuItem_PedidosCancelamentovendas);

        jMenu_Pedidos.add(jMenu_PedidosVendas);

        jMenuBar_Menu.add(jMenu_Pedidos);

        jMenu_Notasfiscais.setText("Notas Fiscais");
        jMenu_Notasfiscais.setToolTipText("");

        jMenu_NfEntradaNf.setText("Entrada");

        jMenuItem_EmissaoEntradaNf.setText("Emissão");
        jMenuItem_EmissaoEntradaNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EmissaoEntradaNfActionPerformed(evt);
            }
        });
        jMenu_NfEntradaNf.add(jMenuItem_EmissaoEntradaNf);

        jMenuItem_CancelamentoEntradaNf.setText("Cancelamento");
        jMenuItem_CancelamentoEntradaNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CancelamentoEntradaNfActionPerformed(evt);
            }
        });
        jMenu_NfEntradaNf.add(jMenuItem_CancelamentoEntradaNf);

        jMenu_Notasfiscais.add(jMenu_NfEntradaNf);

        jMenu_NfSaidaNf.setText("Saída");

        jMenuItem_EmissaoSaidaNf.setText("Emissão");
        jMenuItem_EmissaoSaidaNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EmissaoSaidaNfActionPerformed(evt);
            }
        });
        jMenu_NfSaidaNf.add(jMenuItem_EmissaoSaidaNf);

        jMenuItem_CancelamentoSaidaNf.setText("Cancelamento");
        jMenuItem_CancelamentoSaidaNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CancelamentoSaidaNfActionPerformed(evt);
            }
        });
        jMenu_NfSaidaNf.add(jMenuItem_CancelamentoSaidaNf);

        jMenu_Notasfiscais.add(jMenu_NfSaidaNf);

        jMenuBar_Menu.add(jMenu_Notasfiscais);

        jMenu_Consultas.setText("Consultas");

        jMenuItem_ConsultasCidades.setText("Cidades");
        jMenuItem_ConsultasCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultasCidadesActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItem_ConsultasCidades);

        jMenuItem_ConsultasClientes.setText("Clientes");
        jMenuItem_ConsultasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultasClientesActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItem_ConsultasClientes);

        jMenuItem_ConsultasFuncionarios.setText("Funcionários");
        jMenuItem_ConsultasFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultasFuncionariosActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItem_ConsultasFuncionarios);

        jMenuItem_ConsultasNf.setText("Notas Fiscais");
        jMenuItem_ConsultasNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultasNfActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItem_ConsultasNf);

        jMenuItemConsultasPedidos.setText("Pedidos");
        jMenuItemConsultasPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultasPedidosActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItemConsultasPedidos);

        jMenuItemConsultasProdutos.setText("Produtos");
        jMenuItemConsultasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultasProdutosActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItemConsultasProdutos);

        jMenuItem_ConsultasUsuarios.setText("Usuários");
        jMenuItem_ConsultasUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultasUsuariosActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jMenuItem_ConsultasUsuarios);

        jMenuBar_Menu.add(jMenu_Consultas);

        jMenu_Relatorios.setText("Relatórios");

        jMenuItem_RelatoriosCidades.setText("Cidades");
        jMenuItem_RelatoriosCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosCidadesActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosCidades);

        jMenuItem_RelatoriosClientes.setText("Clientes");
        jMenuItem_RelatoriosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosClientesActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosClientes);

        jMenuItem_RelatoriosFuncionarios.setText("Funcionários");
        jMenuItem_RelatoriosFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosFuncionariosActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosFuncionarios);

        jMenuItem_RelatoriosNf.setText("Notas Fiscais");
        jMenuItem_RelatoriosNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosNfActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosNf);

        jMenuItem_RelatoriosPedidos.setText("Pedidos");
        jMenuItem_RelatoriosPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosPedidosActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosPedidos);

        jMenuItem_RelatoriosProdutos.setText("Produtos");
        jMenuItem_RelatoriosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosProdutosActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosProdutos);

        jMenuItem_RelatoriosUsuarios.setText("Usuários");
        jMenuItem_RelatoriosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RelatoriosUsuariosActionPerformed(evt);
            }
        });
        jMenu_Relatorios.add(jMenuItem_RelatoriosUsuarios);

        jMenuBar_Menu.add(jMenu_Relatorios);

        jMenu_Sobre.setText("Sobre");

        jMenuItem_SobreSistema.setText("Sistema");
        jMenuItem_SobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SobreSistemaActionPerformed(evt);
            }
        });
        jMenu_Sobre.add(jMenuItem_SobreSistema);

        jMenuItem_SobreAjuda.setText("Ajuda");
        jMenuItem_SobreAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SobreAjudaActionPerformed(evt);
            }
        });
        jMenu_Sobre.add(jMenuItem_SobreAjuda);

        jMenuBar_Menu.add(jMenu_Sobre);

        setJMenuBar(jMenuBar_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 587, Short.MAX_VALUE)
        );

        setBounds(0, 0, 977, 647);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroFuncionariosActionPerformed
        Cadastro.Funcionarios funcionarios = new Cadastro.Funcionarios();
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastroFuncionariosActionPerformed

    private void jMenuItem_CadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroUsuariosActionPerformed
        Cadastro.Usuarios usuarios = new Cadastro.Usuarios();
        usuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastroUsuariosActionPerformed

    private void jMenuItem_CadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroClientesActionPerformed
        Cadastro.Clientes clientes = new Cadastro.Clientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastroClientesActionPerformed

    private void jMenuItem_CadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroProdutosActionPerformed
        Cadastro.Produtos produtos = new Cadastro.Produtos();
        produtos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastroProdutosActionPerformed

    private void jMenuItem_PedidosCancelamentoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidosCancelamentoComprasActionPerformed
        Pedidos_Compra.Cancelamento cancelamentoPedidosCompra = new Pedidos_Compra.Cancelamento();
        cancelamentoPedidosCompra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PedidosCancelamentoComprasActionPerformed

    private void jMenuItem_ConsultasCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultasCidadesActionPerformed
        Consultas.Cidades cidades = new Consultas.Cidades();
        cidades.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultasCidadesActionPerformed

    private void jMenuItem_CancelamentoEntradaNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CancelamentoEntradaNfActionPerformed
        Notas_Fiscais_Entrada.Cancelamento cancelamentoNotaFiscalEntrada = new Notas_Fiscais_Entrada.Cancelamento();
        cancelamentoNotaFiscalEntrada.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CancelamentoEntradaNfActionPerformed

    private void jMenuItem_PedidosEmissaoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidosEmissaoVendasActionPerformed
        Pedidos_Venda.Emissao emissaoPedidosVenda = new Pedidos_Venda.Emissao();
        emissaoPedidosVenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PedidosEmissaoVendasActionPerformed

    private void jMenuItem_PedidosLiberacaovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidosLiberacaovendasActionPerformed
        Pedidos_Venda.Liberacao liberacaoPedidosVenda = new Pedidos_Venda.Liberacao();
        liberacaoPedidosVenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PedidosLiberacaovendasActionPerformed

    private void jMenuItem_PedidosLiberacaoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidosLiberacaoComprasActionPerformed
        Pedidos_Compra.Liberacao liberacaoPedidosCompra = new Pedidos_Compra.Liberacao();
        liberacaoPedidosCompra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PedidosLiberacaoComprasActionPerformed

    private void jMenuItem_SobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SobreSistemaActionPerformed
        Sobre.Sistema sistema = new Sobre.Sistema();
        sistema.setVisible(true);
    }//GEN-LAST:event_jMenuItem_SobreSistemaActionPerformed

    private void jMenuItem_CadastroCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroCargosActionPerformed
        Cadastro.Cargos cargos = new Cadastro.Cargos();
        cargos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastroCargosActionPerformed

    private void jMenuItem_CadastroCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroCidadesActionPerformed
        Cadastro.Cidades cidades = new Cadastro.Cidades();
        cidades.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastroCidadesActionPerformed

    private void jMenuItem_EmissaoEntradaNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EmissaoEntradaNfActionPerformed
        Notas_Fiscais_Entrada.Emissao emissaoNotaFiscalEntrada = new Notas_Fiscais_Entrada.Emissao();
        emissaoNotaFiscalEntrada.setVisible(true);
    }//GEN-LAST:event_jMenuItem_EmissaoEntradaNfActionPerformed

    private void jMenuItem_EmissaoSaidaNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EmissaoSaidaNfActionPerformed
        Notas_Fiscais_Saida.Emissao emissaoNotaFiscalSaida = new Notas_Fiscais_Saida.Emissao();
        emissaoNotaFiscalSaida.setVisible(true);
    }//GEN-LAST:event_jMenuItem_EmissaoSaidaNfActionPerformed

    private void jMenuItem_CancelamentoSaidaNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CancelamentoSaidaNfActionPerformed
        Notas_Fiscais_Saida.Cancelamento cancelamentoNotaFiscalSaida = new Notas_Fiscais_Saida.Cancelamento();
        cancelamentoNotaFiscalSaida.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CancelamentoSaidaNfActionPerformed

    private void jMenuItem_ConsultasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultasClientesActionPerformed
        Consultas.Clientes clientes = new Consultas.Clientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultasClientesActionPerformed

    private void jMenuItem_ConsultasFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultasFuncionariosActionPerformed
        Consultas.Funcionarios funcionarios = new Consultas.Funcionarios();
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultasFuncionariosActionPerformed

    private void jMenuItem_PedidosEmissaoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidosEmissaoComprasActionPerformed
        Pedidos_Compra.Emissao emissaoPedidosCompra = new Pedidos_Compra.Emissao();
        emissaoPedidosCompra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PedidosEmissaoComprasActionPerformed

    private void jMenuItem_PedidosCancelamentovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidosCancelamentovendasActionPerformed
        Pedidos_Venda.Cancelamento cancelamentoPedidosVenda = new Pedidos_Venda.Cancelamento();
        cancelamentoPedidosVenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PedidosCancelamentovendasActionPerformed

    private void jMenuItem_SobreAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SobreAjudaActionPerformed
        Sobre.Ajuda ajuda = new Sobre.Ajuda();
        ajuda.setVisible(true);
    }//GEN-LAST:event_jMenuItem_SobreAjudaActionPerformed

    private void jMenuItem_ConsultasNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultasNfActionPerformed
        Consultas.Notas_Fiscais_Faturadas notasFiscais = new Consultas.Notas_Fiscais_Faturadas();
        notasFiscais.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultasNfActionPerformed

    private void jMenuItemConsultasPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultasPedidosActionPerformed
       Consultas.Pedidos_em_aberto pedidos = new Consultas.Pedidos_em_aberto();
       pedidos.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultasPedidosActionPerformed

    private void jMenuItemConsultasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultasProdutosActionPerformed
        Consultas.Produtos produtos = new Consultas.Produtos();
        produtos.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultasProdutosActionPerformed

    private void jMenuItem_ConsultasUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultasUsuariosActionPerformed
        Consultas.Usuarios usuarios = new Consultas.Usuarios();
        usuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultasUsuariosActionPerformed

    private void jMenuItem_RelatoriosCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosCidadesActionPerformed
        Relatorios.Rel_cidades cidades = new Rel_cidades();
        cidades.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosCidadesActionPerformed

    private void jMenuItem_RelatoriosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosClientesActionPerformed
        Relatorios.Rel_clientes clientes = new Rel_clientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosClientesActionPerformed

    private void jMenuItem_RelatoriosFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosFuncionariosActionPerformed
        Relatorios.Rel_funcionarios funcionarios = new Rel_funcionarios();
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosFuncionariosActionPerformed

    private void jMenuItem_RelatoriosNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosNfActionPerformed
        Relatorios.Rel_notas_fiscais nf = new Rel_notas_fiscais();
        nf.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosNfActionPerformed

    private void jMenuItem_RelatoriosPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosPedidosActionPerformed
        Relatorios.Rel_pedidos pedidos = new Rel_pedidos();
        pedidos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosPedidosActionPerformed

    private void jMenuItem_RelatoriosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosProdutosActionPerformed
        Relatorios.Rel_produtos produtos = new Rel_produtos();
        produtos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosProdutosActionPerformed

    private void jMenuItem_RelatoriosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RelatoriosUsuariosActionPerformed
        Relatorios.Rel_usuarios usuarios = new Rel_usuarios();
        usuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RelatoriosUsuariosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        UnicaConexao con = new UnicaConexao();
        con.conectar();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundoMenu;
    private javax.swing.JMenuBar jMenuBar_Menu;
    private javax.swing.JMenuItem jMenuItemConsultasPedidos;
    private javax.swing.JMenuItem jMenuItemConsultasProdutos;
    private javax.swing.JMenuItem jMenuItem_CadastroCargos;
    private javax.swing.JMenuItem jMenuItem_CadastroCidades;
    private javax.swing.JMenuItem jMenuItem_CadastroClientes;
    private javax.swing.JMenuItem jMenuItem_CadastroFuncionarios;
    private javax.swing.JMenuItem jMenuItem_CadastroProdutos;
    private javax.swing.JMenuItem jMenuItem_CadastroUsuarios;
    private javax.swing.JMenuItem jMenuItem_CancelamentoEntradaNf;
    private javax.swing.JMenuItem jMenuItem_CancelamentoSaidaNf;
    private javax.swing.JMenuItem jMenuItem_ConsultasCidades;
    private javax.swing.JMenuItem jMenuItem_ConsultasClientes;
    private javax.swing.JMenuItem jMenuItem_ConsultasFuncionarios;
    private javax.swing.JMenuItem jMenuItem_ConsultasNf;
    private javax.swing.JMenuItem jMenuItem_ConsultasUsuarios;
    private javax.swing.JMenuItem jMenuItem_EmissaoEntradaNf;
    private javax.swing.JMenuItem jMenuItem_EmissaoSaidaNf;
    private javax.swing.JMenuItem jMenuItem_PedidosCancelamentoCompras;
    private javax.swing.JMenuItem jMenuItem_PedidosCancelamentovendas;
    private javax.swing.JMenuItem jMenuItem_PedidosEmissaoCompras;
    private javax.swing.JMenuItem jMenuItem_PedidosEmissaoVendas;
    private javax.swing.JMenuItem jMenuItem_PedidosLiberacaoCompras;
    private javax.swing.JMenuItem jMenuItem_PedidosLiberacaovendas;
    private javax.swing.JMenuItem jMenuItem_RelatoriosCidades;
    private javax.swing.JMenuItem jMenuItem_RelatoriosClientes;
    private javax.swing.JMenuItem jMenuItem_RelatoriosFuncionarios;
    private javax.swing.JMenuItem jMenuItem_RelatoriosNf;
    private javax.swing.JMenuItem jMenuItem_RelatoriosPedidos;
    private javax.swing.JMenuItem jMenuItem_RelatoriosProdutos;
    private javax.swing.JMenuItem jMenuItem_RelatoriosUsuarios;
    private javax.swing.JMenuItem jMenuItem_SobreAjuda;
    private javax.swing.JMenuItem jMenuItem_SobreSistema;
    private javax.swing.JMenu jMenu_Cadastro;
    private javax.swing.JMenu jMenu_Consultas;
    private javax.swing.JMenu jMenu_NfEntradaNf;
    private javax.swing.JMenu jMenu_NfSaidaNf;
    private javax.swing.JMenu jMenu_Notasfiscais;
    private javax.swing.JMenu jMenu_Pedidos;
    private javax.swing.JMenu jMenu_PedidosCompras;
    private javax.swing.JMenu jMenu_PedidosVendas;
    private javax.swing.JMenu jMenu_Relatorios;
    private javax.swing.JMenu jMenu_Sobre;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
