/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro;

import Menu.VariaveisPublicas;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronde
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_codigo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_descricao = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        lbl_quantidade = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        lbl_pesoLiquido = new javax.swing.JLabel();
        txt_pesoLiquido = new javax.swing.JTextField();
        lbl_pesoBruto = new javax.swing.JLabel();
        txt_pesoBruto = new javax.swing.JTextField();
        lbl_unidadeMedida = new javax.swing.JLabel();
        txt_unidadeMedida = new javax.swing.JTextField();
        lbl_status = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox();
        lbl_observacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        at_observacoes = new javax.swing.JTextArea();
        btn_sair = new javax.swing.JButton();
        btn_gravar = new javax.swing.JButton();
        btn_incluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_codigo.setText("Código");

        txt_codigo.setEnabled(false);

        lbl_descricao.setText("Descrição");

        lbl_quantidade.setText("Quantidade");

        lbl_pesoLiquido.setText("Peso Liq.");

        lbl_pesoBruto.setText("Peso Br.");

        lbl_unidadeMedida.setText("Un. Medida");

        lbl_status.setText("Status");

        cb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        lbl_observacoes.setText("Observações");

        at_observacoes.setColumns(20);
        at_observacoes.setRows(5);
        jScrollPane1.setViewportView(at_observacoes);

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/32/sair.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/32/avancar.png"))); // NOI18N
        btn_gravar.setText("Gravar");
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });

        btn_incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/32/incluir.png"))); // NOI18N
        btn_incluir.setText("Incluir");
        btn_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_incluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_codigo)
                .addGap(18, 18, 18)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_descricao))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_quantidade)
                .addGap(33, 33, 33)
                .addComponent(lbl_pesoLiquido)
                .addGap(44, 44, 44)
                .addComponent(lbl_pesoBruto)
                .addGap(40, 40, 40)
                .addComponent(lbl_unidadeMedida)
                .addGap(56, 56, 56)
                .addComponent(lbl_status))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_pesoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_pesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txt_unidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_observacoes))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btn_incluir)
                .addGap(6, 6, 6)
                .addComponent(btn_gravar)
                .addGap(6, 6, 6)
                .addComponent(btn_sair))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_codigo))
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lbl_descricao)
                .addGap(6, 6, 6)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_quantidade)
                    .addComponent(lbl_pesoLiquido)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_pesoBruto)
                        .addComponent(lbl_unidadeMedida))
                    .addComponent(lbl_status))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lbl_observacoes)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_incluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_gravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(489, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        gravar();
    }//GEN-LAST:event_btn_gravarActionPerformed

    private void btn_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_incluirActionPerformed
        limpacampos();
        habilitacampos();
    }//GEN-LAST:event_btn_incluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_codigo.setEditable(false);
    }//GEN-LAST:event_formWindowOpened

    private void limpacampos(){
        txt_descricao.setText("");
        txt_quantidade.setText("");
        txt_pesoLiquido.setText("");
        txt_pesoBruto.setText("");
        txt_unidadeMedida.setText("");
        cb_status.setSelectedIndex(-1);
        at_observacoes.setText("");
    }
    
    private void habilitacampos(){
        txt_descricao.setEditable(true);
        txt_quantidade.setEditable(true);
        txt_pesoLiquido.setEditable(true);
        txt_pesoBruto.setEditable(true);
        txt_unidadeMedida.setEditable(true);
        cb_status.setEditable(true);
        at_observacoes.setEditable(true);
    }
    
    private void gravar(){
        String xDescricao = txt_descricao.getText();
        Double xQtd = Double.valueOf(txt_quantidade.getText());
        Double xPesoLiquido = Double.valueOf(txt_pesoLiquido.getText());
        Double xPesoBruto = Double.valueOf(txt_pesoBruto.getText());
        String xUnidadeMedida = txt_quantidade.getText();
        String xStatus = cb_status.getSelectedItem().toString();
        String xObservacoes = at_observacoes.getText();
        
        try{
            String sql = "insert into CADASTRO_PRODUTOS(descricao, qtde, peso_liq, peso_br, un_medida, status, observacoes)"
                    + "values('"+ xDescricao + "', '" + xQtd + "', '" + xPesoLiquido + "', '" + xPesoBruto + "', '" + xUnidadeMedida + "', '" + xStatus + "', '" + xObservacoes + "')";
            System.out.println(sql);
            Statement stm = VariaveisPublicas.ConexaoPadrao.createStatement();
            stm.executeUpdate(sql);
            stm.close();
            JOptionPane.showMessageDialog(rootPane, "Produto Cadastrado!");
            limpacampos();
        }
        
        catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(Produtos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea at_observacoes;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_incluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JComboBox cb_status;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_observacoes;
    private javax.swing.JLabel lbl_pesoBruto;
    private javax.swing.JLabel lbl_pesoLiquido;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_unidadeMedida;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_pesoBruto;
    private javax.swing.JTextField txt_pesoLiquido;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JTextField txt_unidadeMedida;
    // End of variables declaration//GEN-END:variables
}
